---
title: "world_population"
author: "Nathan Shane"
date: "2023-09-22"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
world_data<- read.csv("world_population.csv")

world_data <- world_data %>% 
  rename(population_2020 = Population..2020.,
         Country = Country.Other,
         yearly_change = Yearly.Change,
         net_change = Net.Change,
         pop_density = Density..P.Km..,
         land_area = Land.Area..Km..,
         mig_net = Migrants..net.,
         fert_rate = Fert..Rate,
         med_age = Med..Age,
         urban_pop = Urban.Pop..,
          world_share = World.Share)  %>%
   add_row(Country = "Greenland", population_2020 = 56367) %>%
   add_row( Country = "Somaliland", population_2020 = 16537016)


suicide_rate <- read.csv("Suicide rate.csv")
suicide_rate$Country[suicide_rate$Country == "Democratic Republic of the Congo"] <- "DR Congo"
suicide_rate$Country[suicide_rate$Country == "Cape Verde"] <- "Cabo Verde"
suicide_rate$Country[suicide_rate$Country == "Czech Republic"] <- "Czech Republic (Czechia)"
suicide_rate$Country[suicide_rate$Country == "East Timor"] <- "Timor-Leste"
suicide_rate$Country[suicide_rate$Country == "Ivory Coast"] <- "Côte d'Ivoire"
suicide_rate$Country[suicide_rate$Country == "Republic of the Congo"] <- "Congo"
suicide_rate$Country[suicide_rate$Country == "Saint Vincent and the Grenadines"] <- "St. Vincent & Grenadines"
suicide_rate$Country[suicide_rate$Country == "The Bahamas"] <- "Bahamas"
suicide_rate$Country[suicide_rate$Country == "The Gambia"] <- "Gambia"
  
GDP <- read.csv("GDP per capita.csv")
GDP$Country[GDP$Country == "Democratic Republic of the Congo"] <- "DR Congo"
GDP$Country[GDP$Country == "Cape Verde"] <- "Cabo Verde"
GDP$Country[GDP$Country == "Czech Republic"] <- "Czech Republic (Czechia)"
GDP$Country[GDP$Country == "East Timor"] <- "Timor-Leste"
GDP$Country[GDP$Country == "Ivory Coast"] <- "Côte d'Ivoire"
GDP$Country[GDP$Country == "Republic of the Congo"] <- "Congo"
GDP$Country[GDP$Country == "Saint Vincent and the Grenadines"] <- "St. Vincent & Grenadines"
GDP$Country[GDP$Country == "The Bahamas"] <- "Bahamas"
GDP$Country[GDP$Country == "The Gambia"] <- "Gambia"

life_expect <- read.csv("Life expectancy.csv")
life_expect$Country[life_expect$Country == "Democratic Republic of the Congo"] <- "DR Congo"
life_expect$Country[life_expect$Country == "Cape Verde"] <- "Cabo Verde"
life_expect$Country[life_expect$Country == "Czech Republic"] <- "Czech Republic (Czechia)"
life_expect$Country[life_expect$Country == "East Timor"] <- "Timor-Leste"
life_expect$Country[life_expect$Country == "Ivory Coast"] <- "Côte d'Ivoire"
life_expect$Country[life_expect$Country == "Republic of the Congo"] <- "Congo"
life_expect$Country[life_expect$Country == "Saint Vincent and the Grenadines"] <- "St. Vincent & Grenadines"
life_expect$Country[life_expect$Country == "The Bahamas"] <- "Bahamas"
life_expect$Country[life_expect$Country == "The Gambia"] <- "Gambia"


world_data <- left_join(world_data, suicide_rate, by = "Country")
world_data <- left_join(world_data, GDP, by = "Country")
world_data <- left_join(world_data, life_expect, by = "Country")

world_data <- world_data %>% 
  select(-c(ISO.code.x, ISO.code.y, ISO.code)) %>% 
  rename(suicide_rate = Suicide.rate,
         gdp_per_capita = GDP.per.capita,
         life_expect = Life.expectancy)

world_data$Country[world_data$Country == "United States"] <- "United States of America"

world_data$Country[world_data$Country == "DR Congo"] <- "Dem. Rep. Congo"

world_data$Country[world_data$Country == "South Sudan"] <- "S. Sudan"

world_data$Country[world_data$Country == "Central African Republic"] <- "Central African Rep."


library(countrycode)

head(world_data)

world_data <- world_data %>% 
  mutate(continent = countrycode(world_data$Country, origin = "country.name", destination = "continent"))

file_path <- paste0(getwd(), "/CLEAN_WORLD_POPULATION_DATA.csv")
write.csv(world_data, file = file_path)

total_population_by_continent <- world_data %>%
  group_by(continent) %>%
  summarise(Total_Population = sum(population_2020))

total_population_by_continent <- na.omit(total_population_by_continent)

file_path_continent_pop <- paste0(getwd(), "/Pop_by_continent.csv")
write.csv(total_population_by_continent, file = file_path_continent_pop)

```




```{r}
time_series_data <- read.csv("world_population_2.csv")

population_by_continent <- time_series_data %>%
  group_by(Continent) %>%
  summarise(Population_2022 = sum(X2022.Population),
            Population_2015 = sum(X2015.Population),
            Population_2010 = sum(X2010.Population),
            Population_2000 = sum(X2000.Population))

population_by_continent <- population_by_continent %>% 
  pivot_longer(!Continent, names_to = "Year", values_to = "Population")

population_by_continent$Year[population_by_continent$Year == "Population_2022"] <- 2022
population_by_continent$Year[population_by_continent$Year == "Population_2015"] <- 2015
population_by_continent$Year[population_by_continent$Year == "Population_2010"] <- 2010
population_by_continent$Year[population_by_continent$Year == "Population_2000"] <- 2000
population_by_continent$Year = as.numeric(population_by_continent$Year)


head(population_by_continent)

file_path_continent_pop <- paste0(getwd(), "/Pop_by_continent.csv")
write.csv(population_by_continent, file = file_path_continent_pop)
```

```{r}
world_pop_data <- read.csv("world_population_2.csv")

world_pop_data$Country.Territory[world_pop_data$Country.Territory == "United States"] <- "United States of America"

world_pop_data$Country.Territory[world_pop_data$Country.Territory == "DR Congo"] <- "Dem. Rep. Congo"

world_pop_data$Country.Territory[world_pop_data$Country.Territory == "South Sudan"] <- "S. Sudan"

world_pop_data$Country.Territory[world_pop_data$Country.Territory == "Central African Republic"] <- "Central African Rep."

world_pop_data <- world_pop_data %>% 
  rename(Growth_Rate = Growth.Rate,
         Country = Country.Territory)


file_path_world_pop_diff_year <- paste0(getwd(), "/Pop_by_country_years.csv")
write.csv(world_pop_data, file = file_path_world_pop_diff_year)

```

```{r}
clean_world_population <- read.csv("CLEAN_WORLD_POPULATION_DATA.csv")

library(countrycode)

north_american_countries <- c(
  "Canada", "United States", "Mexico", "Antigua and Barbuda", 
  "Bahamas", "Barbados", "Belize", "Costa Rica", "Cuba", 
  "Dominica", "Dominican Republic", "El Salvador", "Grenada", 
  "Guatemala", "Haiti", "Honduras", "Jamaica", "Nicaragua", 
  "Panama", "Saint Kitts and Nevis", "Saint Lucia", 
  "Saint Vincent and the Grenadines", "Trinidad and Tobago"
)

south_american_countries <- c(
  "Argentina", "Bolivia", "Brazil", "Chile", "Colombia", 
  "Ecuador", "Guyana", "Paraguay", "Peru", "Suriname", 
  "Uruguay", "Venezuela"
)

clean_world_population <- clean_world_population %>% 
          mutate( continent = ifelse(continent == "Americas" & Country %in% north_american_countries, "North America", continent),
         continent = ifelse(continent == "Americas" & Country %in% south_american_countries, "South America", continent))


file_path <- paste0(getwd(), "/CLEAN_WORLD_POPULATION_DATA.csv")
write.csv(clean_world_population, file = file_path)


```

```{r}

clean_world_population_2 <- na.omit(clean_world_population)
clean_world_population_2 <- clean_world_population_2 %>% mutate( continent = ifelse(continent == "Americas", NA, continent))
clean_world_population_2 <- na.omit(clean_world_population_2)

file_path <- paste0(getwd(), "/CLEAN_WORLD_POPULATION_DATA_NO_NA.csv")
write.csv(clean_world_population_2, file = file_path)
```


```{r}
pop_year_2 <- read.csv("pop_by_country_years.csv")
pop_year_2 <- pop_year_2 %>% 
  pivot_longer(cols = c("X2022.Population","X2015.Population","X2010.Population","X2000.Population","X1990.Population"),names_to = "Year", values_to = "Population")

pop_year_2$Year[pop_year_2$Year == "X2022.Population"] <- 2022
pop_year_2$Year[pop_year_2$Year == "X2015.Population"] <- 2015
pop_year_2$Year[pop_year_2$Year == "X2010.Population"] <- 2010
pop_year_2$Year[pop_year_2$Year == "X2000.Population"] <- 2000
pop_year_2$Year[pop_year_2$Year == "X1990.Population"] <- 1990

pop_year_2$Year <- as.numeric(pop_year_2$Year)

pop_year_2 <- pop_year_2 %>% 
  select(Year, Population, Continent)
head(pop_year_2)

groupped_data <- pop_year_2 %>% 
group_by(Continent, Year) %>% 
  summarise(Total_pop = sum(Population))

groupped_data
file_path <- paste0(getwd(), "/Continent_pop_over_years.csv")
write.csv(groupped_data, file = file_path)

```


```{r}
clean_world_data_pie <- read.csv("CLEAN_WORLD_POPULATION_DATA_NO_NA.csv")
clean_world_data_pie <- clean_world_data_pie %>% 
  mutate(dup_population_2020 = population_2020)

head(clean_world_data_pie)

file_path <- paste0(getwd(), "/CLEAN_WORLD_POPULATION_DATA_NO_NA.csv")
write.csv(clean_world_data_pie, file = file_path)
```

```{r}
continent_pie <- read.csv("Continent_pop_over_years.csv")
continent_pie$Year <- as.character(continent_pie$Year)
head(continent_pie)

file_path <- paste0(getwd(), "/Continent_pop_over_years.csv")
write.csv(continent_pie, file = file_path)
```

```{r}
freedom_data <- read.csv("freedom_data.csv")

library(countrycode)
head(freedom_data)

north_american_countries <- c(
  "Canada", "United States", "Mexico", "Antigua and Barbuda", 
  "Bahamas", "Barbados", "Belize", "Costa Rica", "Cuba", 
  "Dominica", "Dominican Republic", "El Salvador", "Grenada", 
  "Guatemala", "Haiti", "Honduras", "Jamaica", "Nicaragua", 
  "Panama", "Saint Kitts and Nevis", "Saint Lucia", 
  "Saint Vincent and the Grenadines", "Trinidad and Tobago"
)

south_american_countries <- c(
  "Argentina", "Bolivia", "Brazil", "Chile", "Colombia", 
  "Ecuador", "Guyana", "Paraguay", "Peru", "Suriname", 
  "Uruguay", "Venezuela"
)

freedom_data <- freedom_data %>% 
  mutate(continent = countrycode(freedom_data$Country.Territory, origin = "country.name", destination = "continent")) %>% 
  rename(Country = Country.Territory)

freedom_data <- freedom_data %>% 
          mutate( continent = ifelse(continent == "Americas" & Country %in% north_american_countries, "North America", continent),
         continent = ifelse(continent == "Americas" & Country %in% south_american_countries, "South America", continent))

head(freedom_data)
clean_freedom_data <- freedom_data %>% 
  group_by(continent, Edition) %>% 
  select(continent, Edition, CL.rating, PR.rating)


clean_freedom_data <- clean_freedom_data %>% mutate( continent = ifelse(continent == "Americas", NA, continent))
clean_freedom_data <- na.omit(clean_freedom_data)

clean_freedom_data <- clean_freedom_data %>% group_by(continent, Edition) %>% 
  summarise(avg_CL_Rating = mean(CL.rating),
            avg_PR_Rating = mean(PR.rating))


head(clean_freedom_data)
file_path <- paste0(getwd(), "/freedom_data.csv")
write.csv(clean_freedom_data, file = file_path)
```

```{r}
gapminder_data <- read.csv("gapminder_alcohol.csv")

gapminder_data <- gapminder_data %>% select(country, employrate)

gapminder_data <- gapminder_data %>% 
  mutate(Unemploy_rate = 100-employrate)

gapminder_data$country[gapminder_data$country == "United States"] <- "United States of America"

gapminder_data$country[gapminder_data$country == "Congo, Dem. Rep."] <- "Dem. Rep. Congo"

gapminder_data$country[gapminder_data$country == "South Sudan"] <- "S. Sudan"

gapminder_data$country[gapminder_data$country == "Central African Republic"] <- "Central African Rep."

file_path <- paste0(getwd(), "/gapminder_alcohol.csv")
write.csv(gapminder_data, file = file_path)

```

